name: GoSec Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gosec-scan:
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install Go
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # 3. Run GoSec
      - name: Run GoSec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          $HOME/go/bin/gosec ./...