name: CI Pipeline with Security Tools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-22.04

    steps:
      # 1. Install tar utility
      - name: Install tar
        run: sudo apt-get update && sudo apt-get install -y tar

      # 2. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 3. Install Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # 4. Install Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' # Adjust the version based on your project requirements

      - name: Verify Go Installation
        run: go version

      # 5. Run Semgrep
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/r2c-ci"

      # 6. Run GoSec
      - name: Run GoSec
        run: |
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE
          ./gosec ./...

      # 7. Run SonarCloud Analysis
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Add your SonarCloud token in the GitHub repository secrets
        with:
          args: >
            -Dsonar.projectKey=yasser1azizi
            -Dsonar.organization=yasser1azizi_awesomeProject
            -Dsonar.sources=src \
            -Dsonar.java.binaries=./build/classes # Adjust if not a Java project

      # 8. Run Snyk for Vulnerability Scanning
      - name: Run Snyk to Check for Vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high