name: SonarQube Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install Java (Required for SonarQube)
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. Run SonarQube Analysis
      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=your_organization \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.github.repository=${{ github.repository }} \
            -Dsonar.github.prKey=${{ github.event.pull_request.number }}