name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Java (Required for SonarScanner CLI)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Install SonarScanner CLI
      - name: Install SonarScanner CLI
        run: |
          curl -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip -d $HOME
          echo "$HOME/sonar-scanner-4.8.0.2856-linux/bin" >> $GITHUB_PATH

      # 4. Run SonarCloud Analysis
      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PULL_REQUEST_KEY: ${{ github.event.pull_request.number }}
          PULL_REQUEST_BRANCH: ${{ github.head_ref }}
          PULL_REQUEST_BASE: ${{ github.base_ref }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=yasser1azizi_awesomeProject \
            -Dsonar.organization=yasser1azizi \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.sources=. \
            -Dsonar.pullrequest.key="$PULL_REQUEST_KEY" \
            -Dsonar.pullrequest.branch="$PULL_REQUEST_BRANCH" \
            -Dsonar.pullrequest.base="$PULL_REQUEST_BASE"

      # Optional: Display Logs
      - name: Display SonarScanner Logs
        run: cat .scannerwork/report-task.txt